-- 1. Create Lookup/Parent Tables first
CREATE TABLE STARS_CURRENCY (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CURRENCY_NAME VARCHAR(50) NOT NULL,
    CURRENCY_CODE VARCHAR(10) NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(100) DEFAULT current_user,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE STARS_REGION (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REGION_NAME VARCHAR(50) NOT NULL,
    REGION_CODE VARCHAR(10) NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(100) DEFAULT current_user,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE STARS_FUNDING_VEHICLE (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FUNDING_VEHICLE_NAME VARCHAR(50) NOT NULL,
    FUNDING_VEHICLE_CODE VARCHAR(10) NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(100) DEFAULT current_user,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW()
);


-- Seed Currencies
INSERT INTO STARS_CURRENCY (CURRENCY_NAME, CURRENCY_CODE, IS_ACTIVE) VALUES
('US Dollar', 'USD', TRUE),
('Euro', 'EUR', TRUE),
('British Pound', 'GBP', TRUE),
('Japanese Yen', 'JPY', TRUE),
('Canadian Dollar', 'CAD', TRUE);

-- Seed Regions
INSERT INTO STARS_REGION (REGION_NAME, REGION_CODE, IS_ACTIVE) VALUES
('North America', 'NA', TRUE),
('Europe, Middle East, Africa', 'EMEA', TRUE),
('Asia Pacific', 'APAC', TRUE),
('Latin America', 'LATAM', TRUE);

-- Seed Funding Vehicles
INSERT INTO STARS_FUNDING_VEHICLE (FUNDING_VEHICLE_NAME, FUNDING_VEHICLE_CODE, IS_ACTIVE) VALUES
('Growth Equity Fund I', 'GEF1', TRUE),
('Real Estate Trust', 'REIT', TRUE),
('Venture Capital LP', 'VCLP', TRUE),
('Strategic Debt Fund', 'SDF', TRUE),
('Infrastructure Fund B', 'IFB', TRUE);